[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]
evm_version = "shanghai"

[rpc_endpoints]
chain_a = "http://127.0.0.1:8545"
chain_b = "http://127.0.0.1:9545"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
